version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        ANALYZE: ${ANALYZE}
        PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      ANALYZE: ${ANALYZE}
      PORT: ${PORT}
